### ISSUE TITLE
Add support for multiple users

### ISSUE THREAD

**Issue by jessebot** [jessebot/coturn-chart#14]
## Describe your Issue
I'd like to support adding more than one user to match what is possible in the [coturn/coturn:`examples/etc/turnserver.conf`](https://github.com/coturn/coturn/blob/d7db17f048675f46fc2b30827813eeaf0c822fb2/examples/etc/turnserver.conf#L256-L280)

We should probably convert this into an array: https://github.com/jessebot/coturn-chart/blob/8650cf1ce74ec2a2dc5a720235779c58fb9eefe2/charts/coturn/values.yaml#L128-L140

The array in the values.yaml could look like this:

```yaml
# most coturn config parameters that you really need
coturn:
  users:
   - username:
      password:
      secretKeys:
        username: username
        password: password
```

The question is how do we handle this securely? Right now, these values get passed into a secret, to avoid having plain text passwords, like this: https://github.com/jessebot/coturn-chart/blob/8650cf1ce74ec2a2dc5a720235779c58fb9eefe2/charts/coturn/templates/auth-secret.yaml#L8-L14

And then they're passed into an init container in the deployment via an env var here: https://github.com/jessebot/coturn-chart/blob/8650cf1ce74ec2a2dc5a720235779c58fb9eefe2/charts/coturn/templates/deployment.yaml#L57-L74

So they can then be concatenated in via [`yq`](https://github.com/mikefarah/yq) here: https://github.com/jessebot/coturn-chart/blob/8650cf1ce74ec2a2dc5a720235779c58fb9eefe2/charts/coturn/templates/deployment.yaml#L119

The issue is I don't know what to do here for the init container. I guess we can just make the secret more complex, or we could change the init container to possibly add the users via actual turnserver cli commands? 🤔  I'm open to suggestions and PRs.
