### ISSUE TITLE
A descriptive title of the issue

### ISSUE THREAD

**Issue by mike-pisman** [jessebot/coturn-chart#72]
## Describe your Issue

Seem there is an issue with pvc... The chart managed to create a `coturn-config` **PVC** with 1Mi storage, the status is *Bound*.

### Logs and Errors

Cannot get any other logs, as the pods stuck in creating state. Need more info regarding the chart...

```console
Back-off restarting failed container add-secret-values-to-config in pod coturn-coturn-5fbc7644d4-bkfpc_coturn(407f1f33-50ea-4564-b945-3bee0ddb58bb)
Back-off restarting failed container add-secret-values-to-config in pod coturn-coturn-5fbc7644d4-bkfpc_coturn(407f1f33-50ea-4564-b945-3bee0ddb58bb)
```

## Describe your Environment

- Kubernetes distribution: 

- Helm Version (or App that manages helm): 

- Helm Chart Version: coturn-4.3.0

- `values.yaml`:

```yaml
coturn:
  realm: "turn.my-domain.com"

  auth:
    existingSecret: "coturn-credentials"
    secretKeys:
      username: "username"
      password: "password"
externalDatabse:
  enabled: true
postgresql:
  enabled: false
  global:
    postgresql:
        # -- name of existing Secret to use for postgresql credentials
        existingSecret: "postgresql-credentials"
        # Names of the keys in existing secret to use for PostgreSQL credentials
        secretKeys:
          hostname: "hostname"
          database: "database"
          username: "username"
          adminPasswordKey: "adminPasswordKey"
          userPasswordKey: "userPasswordKey"

```

## Additional context, if any

I use Ceph Rook( **ceph-rbd** storage class) with an external Ceph cluster, it works well with all of the other resources, including the postgresql deployment.
I use postgresql-ha chart by bitnami.

I also get these warnings when installing the chart
```console
W1027 21:08:45.550307  383281 warnings.go:70] unknown field "spec.template.spec.securityContext.allowPrivilegeEscalation"
W1027 21:08:45.550317  383281 warnings.go:70] unknown field "spec.template.spec.securityContext.capabilities"
W1027 21:08:45.550321  383281 warnings.go:70] unknown field "spec.template.spec.securityContext.readOnlyRootFilesystem"
```

```bash
kubectl get secret -n coturn
NAME                           TYPE                 DATA   AGE
coturn-credentials             Opaque               2      73m
postgresql-credentials         Opaque               5      22m
sh.helm.release.v1.coturn.v1   helm.sh/release.v1   1      8m8s
```

```bash
kubectl describe -n coturn secrets coturn-credentials
Name:         coturn-credentials
Namespace:    coturn
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
password:  16 bytes
username:  6 bytes
```

```bash
kubectl describe -n coturn secrets postgresql-credentials
Name:         postgresql-credentials
Namespace:    coturn
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
adminPasswordKey:  10 bytes
database:          8 bytes
hostname:          10 bytes
userPasswordKey:   11 bytes
username:          6 bytes
```
